/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/status": {
    /** Health check */
    get: {
      responses: {
        /** @description System operational */
        200: {
          content: {
            "application/json": {
              /** @example ok */
              status?: string;
              matcher_queue_depth?: number;
            };
          };
        };
      };
    };
  };
  "/attestation/challenge": {
    /**
     * Request a nonce for device attestation
     * @description Returns a random nonce that the secure enclave must sign to prove liveness/authenticity.
     */
    post: operations["createAttestationChallenge"];
  };
  "/agents/bids": {
    /**
     * Submit an Attention Bid
     * @description Agents (buyers) place a bid for human attention matching specific criteria.
     */
    post: operations["createBid"];
  };
  "/users/session/start": {
    /**
     * Initialize a Selling Session
     * @description Called by Chrome Extension to register availability and price floor before WS connection.
     */
    post: operations["startSession"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    BidRequest: {
      /** @description The URL the user should be looking at (optional context) */
      target_url?: string;
      /** @description Bid amount in micro-USDC */
      max_price_per_second: number;
      /**
       * Format: float
       * @description Minimum engagement score required to pay
       */
      required_attention_score: number;
      /** @default 60 */
      expiry_seconds?: number;
    };
    /** @description Payload sent via WebSocket (informational schema) */
    EngagementEvent: {
      session_id?: string;
      seq?: number;
      timestamp?: number;
      attention_score?: number;
      is_human?: number;
      liveness_score?: number;
      signature?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Request a nonce for device attestation
   * @description Returns a random nonce that the secure enclave must sign to prove liveness/authenticity.
   */
  createAttestationChallenge: {
    responses: {
      /** @description Challenge created */
      201: {
        content: {
          "application/json": {
            /** @description Random base64 string */
            nonce?: string;
            timestamp?: number;
          };
        };
      };
    };
  };
  /**
   * Submit an Attention Bid
   * @description Agents (buyers) place a bid for human attention matching specific criteria.
   */
  createBid: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["BidRequest"];
      };
    };
    responses: {
      /** @description Bid accepted and queued */
      201: {
        content: {
          "application/json": {
            bid_id?: string;
          };
        };
      };
      /** @description Invalid bid parameters */
      400: {
        content: never;
      };
      /** @description Insufficient escrow balance */
      402: {
        content: never;
      };
    };
  };
  /**
   * Initialize a Selling Session
   * @description Called by Chrome Extension to register availability and price floor before WS connection.
   */
  startSession: {
    requestBody: {
      content: {
        "application/json": {
          /** @description User's Solana wallet address */
          pubkey?: string;
          /** @description Min USDC micro-cents per second */
          price_floor_micros?: number;
          /** @description Initial hardware integrity proof */
          device_attestation?: string;
        };
      };
    };
    responses: {
      /** @description Session initialized */
      200: {
        content: {
          "application/json": {
            /** @description JWT to use for WS authentication */
            session_token?: string;
          };
        };
      };
    };
  };
}
